### ISSUE TITLE
[considering] Dev/Staging/Production server containers on the same machine

### ISSUE THREAD

**Issue by DeanAyalon** [DeanAyalon/fms-docker#7]
> Will require forwarding a different port for FileMaker to access, or forwarding it through proxy
> Check if nginx-proxy has the ability to listen on different ports (5003)

Will probably not be ideal for real scenarios, but potentially could help single-machine developers

Current thinking:
```yml
services:
  fms${FMS_ENV:+-}${FMS_ENV} # fms OR fms-$FMS_ENV
# alternative: 
  fms-${FMS_ENV:-prod} # cleaner yml but not as nice of a container name
```
This would lead to an easy quick switch by simply changing the `.env` file, without compose replacing the container

## Alternative
```yml
services:
  fms:
    extends: 
      file: compose.base.yml
      service: fms
    profiles:
      - prod
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      # Is there a way to ensure host1.domain:5003 reaches here in nginx-proxy?
      
  fms-dev:
    ...
  fms-staging:
    ...
```

Would be messy and require many more environment variables, but may allow for easier control without changing env files
